#!/bin/bash
#SBATCH --chdir /scratch/kilian/out/conf_B/C6H4_C6H4/
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --mem 16384
#SBATCH --time 10:00:00

module load gcc/8.4.0 
module load mvapich2/2.3.4 
module load quantum-espresso

echo STARTING AT `date`
name="C6H4_C6H4"
shape="brr"
smearing="n"
python /home/kilian/C3MP/simulations/band_calculation.py $name $shape $smearing
echo FINISHED at `date`
